name: CI Innovatech Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Listar archivos para verificar
        run: ls -R

      - name: Probar construcción Frontend
        run: |
          # Si tu carpeta se llama distinto, cámbialo aquí abajo
          docker build ./front-despacho -t front-test || echo "Error en ruta"
